version: '3.8'
services:
  db:
    container_name: pgdb
    hostname: ${POSTGRES_HOST}
    image: postgres
    ports:
      - "54321:5432"
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./db:/var/lib/postgresql/data/